/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './modal';
const styles_ModalComponent:any[] = ([] as any[]);
export const RenderType_ModalComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ModalComponent,data:{}});
export function View_ModalComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),7,'div',[['class','modal-dialog']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),i0.ɵdid(2,278528,(null as any),
      0,i1.NgClass,[i0.IterableDiffers,i0.KeyValueDiffers,i0.ElementRef,i0.Renderer],
      {klass:[0,'klass'],ngClass:[1,'ngClass']},(null as any)),(_l()(),i0.ɵted(-1,
      (null as any),['\n            '])),(_l()(),i0.ɵeld(4,0,(null as any),(null as any),
      3,'div',[['class','modal-content']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),['\n                '])),
      i0.ɵncd((null as any),0),(_l()(),i0.ɵted(-1,(null as any),['\n            '])),
      (_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵted(-1,(null as any),
          ['\n    ']))],(_ck,_v) => {
    var _co:i2.ModalComponent = _v.component;
    const currVal_0:any = 'modal-dialog';
    const currVal_1:any = _co.getCssClasses();
    _ck(_v,2,0,currVal_0,currVal_1);
  },(null as any));
}
export function View_ModalComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'modal',[['class',
      'modal'],['role','dialog'],['tabindex','-1']],[[2,'fade',(null as any)],[1,'data-keyboard',
      0],[1,'data-backdrop',0]],(null as any),(null as any),View_ModalComponent_0,
      RenderType_ModalComponent)),i0.ɵdid(1,180224,(null as any),0,i2.ModalComponent,
      [i0.ElementRef],(null as any),(null as any))],(null as any),(_ck,_v) => {
    const currVal_0:any = i0.ɵnov(_v,1).fadeClass;
    const currVal_1:any = i0.ɵnov(_v,1).dataKeyboardAttr;
    const currVal_2:any = i0.ɵnov(_v,1).dataBackdropAttr;
    _ck(_v,0,0,currVal_0,currVal_1,currVal_2);
  });
}
export const ModalComponentNgFactory:i0.ComponentFactory<i2.ModalComponent> = i0.ɵccf('modal',
    i2.ModalComponent,View_ModalComponent_Host_0,{animation:'animation',backdrop:'backdrop',
        keyboard:'keyboard',size:'size',cssClass:'cssClass'},{onClose:'onClose',onDismiss:'onDismiss',
        onOpen:'onOpen'},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvZW5pY2hvbHNvbi9Db2RlL25nMi1iczMtbW9kYWwvc3JjL25nMi1iczMtbW9kYWwvY29tcG9uZW50cy9tb2RhbC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9qb2VuaWNob2xzb24vQ29kZS9uZzItYnMzLW1vZGFsL3NyYy9uZzItYnMzLW1vZGFsL2NvbXBvbmVudHMvbW9kYWwudHMiLCJuZzovLy9Vc2Vycy9qb2VuaWNob2xzb24vQ29kZS9uZzItYnMzLW1vZGFsL3NyYy9uZzItYnMzLW1vZGFsL2NvbXBvbmVudHMvbW9kYWwudHMuTW9kYWxDb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2pvZW5pY2hvbHNvbi9Db2RlL25nMi1iczMtbW9kYWwvc3JjL25nMi1iczMtbW9kYWwvY29tcG9uZW50cy9tb2RhbC50cy5Nb2RhbENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8ZGl2IGNsYXNzPVwibW9kYWwtZGlhbG9nXCIgW25nQ2xhc3NdPVwiZ2V0Q3NzQ2xhc3NlcygpXCI+XG4gICAgICAgICAgICA8ZGl2IGNsYXNzPVwibW9kYWwtY29udGVudFwiPlxuICAgICAgICAgICAgICAgIDxuZy1jb250ZW50PjwvbmctY29udGVudD5cbiAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICA8L2Rpdj5cbiAgICAiLCI8bW9kYWw+PC9tb2RhbD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsa0RBQ1E7TUFBQTtNQUFBLGlFQUFBO01BQUE7TUFBQSx5REFBc0Q7TUFBQSxtQ0FDbEQ7TUFBQTtNQUFBLDhCQUEyQjthQUN2QixrQkFBeUI7TUFDdkIsa0RBQ0o7VUFBQTs7SUFKRDtJQUFxQjtJQUExQixXQUFLLFVBQXFCLFNBQTFCOzs7O29CQ0RSO01BQUE7TUFBQTsrQkFBQSxVQUFBO01BQUE7SUFBQTtJQUFBO0lBQUE7SUFBQSxXQUFBLDZCQUFBOzs7Ozs7In0=
