/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './modal-body';
const styles_ModalBodyComponent:any[] = ([] as any[]);
export const RenderType_ModalBodyComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ModalBodyComponent,data:{}});
export function View_ModalBodyComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),3,'div',[['class','modal-body']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,
      (null as any),['\n            '])),i0.ɵncd((null as any),0),(_l()(),i0.ɵted(-1,
      (null as any),['\n        '])),(_l()(),i0.ɵted(-1,(null as any),['\n    ']))],
      (null as any),(null as any));
}
export function View_ModalBodyComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'modal-body',
      ([] as any[]),(null as any),(null as any),(null as any),View_ModalBodyComponent_0,
      RenderType_ModalBodyComponent)),i0.ɵdid(1,49152,(null as any),0,i1.ModalBodyComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const ModalBodyComponentNgFactory:i0.ComponentFactory<i1.ModalBodyComponent> = i0.ɵccf('modal-body',
    i1.ModalBodyComponent,View_ModalBodyComponent_Host_0,{},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvZW5pY2hvbHNvbi9Db2RlL25nMi1iczMtbW9kYWwvc3JjL25nMi1iczMtbW9kYWwvY29tcG9uZW50cy9tb2RhbC1ib2R5Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2pvZW5pY2hvbHNvbi9Db2RlL25nMi1iczMtbW9kYWwvc3JjL25nMi1iczMtbW9kYWwvY29tcG9uZW50cy9tb2RhbC1ib2R5LnRzIiwibmc6Ly8vVXNlcnMvam9lbmljaG9sc29uL0NvZGUvbmcyLWJzMy1tb2RhbC9zcmMvbmcyLWJzMy1tb2RhbC9jb21wb25lbnRzL21vZGFsLWJvZHkudHMuTW9kYWxCb2R5Q29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy9qb2VuaWNob2xzb24vQ29kZS9uZzItYnMzLW1vZGFsL3NyYy9uZzItYnMzLW1vZGFsL2NvbXBvbmVudHMvbW9kYWwtYm9keS50cy5Nb2RhbEJvZHlDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICAgICAgPGRpdiBjbGFzcz1cIm1vZGFsLWJvZHlcIj5cbiAgICAgICAgICAgIDxuZy1jb250ZW50PjwvbmctY29udGVudD5cbiAgICAgICAgPC9kaXY+XG4gICAgIiwiPG1vZGFsLWJvZHk+PC9tb2RhbC1ib2R5PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLGtEQUNRO01BQUE7TUFBQSwwREFBd0I7TUFBQSwwQ0FDcEIsa0JBQXlCO01BQUEsK0JBQ3ZCOzs7O29CQ0hkO01BQUE7bUNBQUEsVUFBQTtNQUFBOzs7In0=
