/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './modal-header';
import * as i3 from './modal';
const styles_ModalHeaderComponent:any[] = ([] as any[]);
export const RenderType_ModalHeaderComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ModalHeaderComponent,data:{}});
function View_ModalHeaderComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),4,'button',[['aria-label',
      'Close'],['class','close'],['data-dismiss','modal'],['type','button']],(null as any),
      [[(null as any),'click']],(_v,en,$event) => {
        var ad:boolean = true;
        var _co:any = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.modal.dismiss()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),['\n                '])),
      (_l()(),i0.ɵeld(2,0,(null as any),(null as any),1,'span',[['aria-hidden','true']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['×'])),(_l()(),i0.ɵted(-1,(null as any),['\n            ']))],
      (null as any),(null as any));
}
export function View_ModalHeaderComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),6,'div',[['class','modal-header']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,
      (null as any),['\n            '])),(_l()(),i0.ɵand(16777216,(null as any),(null as any),
      1,(null as any),View_ModalHeaderComponent_1)),i0.ɵdid(4,16384,(null as any),
      0,i1.NgIf,[i0.ViewContainerRef,i0.TemplateRef],{ngIf:[0,'ngIf']},(null as any)),
      (_l()(),i0.ɵted(-1,(null as any),['\n            '])),i0.ɵncd((null as any),
          0),(_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵted(-1,
          (null as any),['\n    ']))],(_ck,_v) => {
    var _co:i2.ModalHeaderComponent = _v.component;
    const currVal_0:any = _co.showClose;
    _ck(_v,4,0,currVal_0);
  },(null as any));
}
export function View_ModalHeaderComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'modal-header',
      ([] as any[]),(null as any),(null as any),(null as any),View_ModalHeaderComponent_0,
      RenderType_ModalHeaderComponent)),i0.ɵdid(1,49152,(null as any),0,i2.ModalHeaderComponent,
      [i3.ModalComponent],(null as any),(null as any))],(null as any),(null as any));
}
export const ModalHeaderComponentNgFactory:i0.ComponentFactory<i2.ModalHeaderComponent> = i0.ɵccf('modal-header',
    i2.ModalHeaderComponent,View_ModalHeaderComponent_Host_0,{showClose:'show-close'},
    {},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvZW5pY2hvbHNvbi9Db2RlL25nMi1iczMtbW9kYWwvc3JjL25nMi1iczMtbW9kYWwvY29tcG9uZW50cy9tb2RhbC1oZWFkZXIubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvam9lbmljaG9sc29uL0NvZGUvbmcyLWJzMy1tb2RhbC9zcmMvbmcyLWJzMy1tb2RhbC9jb21wb25lbnRzL21vZGFsLWhlYWRlci50cyIsIm5nOi8vL1VzZXJzL2pvZW5pY2hvbHNvbi9Db2RlL25nMi1iczMtbW9kYWwvc3JjL25nMi1iczMtbW9kYWwvY29tcG9uZW50cy9tb2RhbC1oZWFkZXIudHMuTW9kYWxIZWFkZXJDb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2pvZW5pY2hvbHNvbi9Db2RlL25nMi1iczMtbW9kYWwvc3JjL25nMi1iczMtbW9kYWwvY29tcG9uZW50cy9tb2RhbC1oZWFkZXIudHMuTW9kYWxIZWFkZXJDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICAgICAgPGRpdiBjbGFzcz1cIm1vZGFsLWhlYWRlclwiPlxuICAgICAgICAgICAgPGJ1dHRvbiAqbmdJZj1cInNob3dDbG9zZVwiIHR5cGU9XCJidXR0b25cIiBjbGFzcz1cImNsb3NlXCIgZGF0YS1kaXNtaXNzPVwibW9kYWxcIiBhcmlhLWxhYmVsPVwiQ2xvc2VcIiAoY2xpY2spPVwibW9kYWwuZGlzbWlzcygpXCI+XG4gICAgICAgICAgICAgICAgPHNwYW4gYXJpYS1oaWRkZW49XCJ0cnVlXCI+JnRpbWVzOzwvc3Bhbj5cbiAgICAgICAgICAgIDwvYnV0dG9uPlxuICAgICAgICAgICAgPG5nLWNvbnRlbnQ+PC9uZy1jb250ZW50PlxuICAgICAgICA8L2Rpdj5cbiAgICAiLCI8bW9kYWwtaGVhZGVyPjwvbW9kYWwtaGVhZGVyPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDRVk7TUFBQTtNQUFBO1FBQUE7UUFBQTtRQUE4RjtVQUFBO1VBQUE7UUFBQTtRQUE5RjtNQUFBLGdDQUF3SDtNQUNwSDtVQUFBO01BQXlCLHlDQUFjOzs7O29CQUh2RCxrREFDUTtNQUFBO01BQUEsMERBQTBCO01BQUEsbUNBQ3RCO01BQUEscURBQUE7TUFBQTtNQUVTLDZEQUNUO1VBQUEsR0FBeUIsa0RBQ3ZCO1VBQUE7O0lBSk07SUFBUixXQUFRLFNBQVI7Ozs7b0JDRlo7TUFBQTtxQ0FBQSxVQUFBO01BQUE7Ozs7In0=
