/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './modal-footer';
import * as i3 from './modal';
const styles_ModalFooterComponent:any[] = ([] as any[]);
export const RenderType_ModalFooterComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_ModalFooterComponent,data:{}});
function View_ModalFooterComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'button',[['class',
      'btn btn-default'],['data-dismiss','modal'],['type','button']],(null as any),
      [[(null as any),'click']],(_v,en,$event) => {
        var ad:boolean = true;
        var _co:any = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.modal.dismiss()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i0.ɵted(1,(null as any),['','']))],(null as any),
      (_ck,_v) => {
        var _co:any = _v.component;
        const currVal_0:any = _co.dismissButtonLabel;
        _ck(_v,1,0,currVal_0);
      });
}
function View_ModalFooterComponent_2(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'button',[['class',
      'btn btn-primary'],['type','button']],(null as any),[[(null as any),'click']],
      (_v,en,$event) => {
        var ad:boolean = true;
        var _co:any = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.modal.close()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i0.ɵted(1,(null as any),['','']))],(null as any),
      (_ck,_v) => {
        var _co:any = _v.component;
        const currVal_0:any = _co.closeButtonLabel;
        _ck(_v,1,0,currVal_0);
      });
}
export function View_ModalFooterComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),9,'div',[['class','modal-footer']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,
      (null as any),['\n            '])),i0.ɵncd((null as any),0),(_l()(),i0.ɵted(-1,
      (null as any),['\n            '])),(_l()(),i0.ɵand(16777216,(null as any),(null as any),
      1,(null as any),View_ModalFooterComponent_1)),i0.ɵdid(6,16384,(null as any),
      0,i1.NgIf,[i0.ViewContainerRef,i0.TemplateRef],{ngIf:[0,'ngIf']},(null as any)),
      (_l()(),i0.ɵted(-1,(null as any),['\n            '])),(_l()(),i0.ɵand(16777216,
          (null as any),(null as any),1,(null as any),View_ModalFooterComponent_2)),
      i0.ɵdid(9,16384,(null as any),0,i1.NgIf,[i0.ViewContainerRef,i0.TemplateRef],
          {ngIf:[0,'ngIf']},(null as any)),(_l()(),i0.ɵted(-1,(null as any),['\n        '])),
      (_l()(),i0.ɵted(-1,(null as any),['\n    ']))],(_ck,_v) => {
    var _co:i2.ModalFooterComponent = _v.component;
    const currVal_0:any = _co.showDefaultButtons;
    _ck(_v,6,0,currVal_0);
    const currVal_1:any = _co.showDefaultButtons;
    _ck(_v,9,0,currVal_1);
  },(null as any));
}
export function View_ModalFooterComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'modal-footer',
      ([] as any[]),(null as any),(null as any),(null as any),View_ModalFooterComponent_0,
      RenderType_ModalFooterComponent)),i0.ɵdid(1,49152,(null as any),0,i2.ModalFooterComponent,
      [i3.ModalComponent],(null as any),(null as any))],(null as any),(null as any));
}
export const ModalFooterComponentNgFactory:i0.ComponentFactory<i2.ModalFooterComponent> = i0.ɵccf('modal-footer',
    i2.ModalFooterComponent,View_ModalFooterComponent_Host_0,{showDefaultButtons:'show-default-buttons',
        dismissButtonLabel:'dismiss-button-label',closeButtonLabel:'close-button-label'},
    {},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2pvZW5pY2hvbHNvbi9Db2RlL25nMi1iczMtbW9kYWwvc3JjL25nMi1iczMtbW9kYWwvY29tcG9uZW50cy9tb2RhbC1mb290ZXIubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvam9lbmljaG9sc29uL0NvZGUvbmcyLWJzMy1tb2RhbC9zcmMvbmcyLWJzMy1tb2RhbC9jb21wb25lbnRzL21vZGFsLWZvb3Rlci50cyIsIm5nOi8vL1VzZXJzL2pvZW5pY2hvbHNvbi9Db2RlL25nMi1iczMtbW9kYWwvc3JjL25nMi1iczMtbW9kYWwvY29tcG9uZW50cy9tb2RhbC1mb290ZXIudHMuTW9kYWxGb290ZXJDb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2pvZW5pY2hvbHNvbi9Db2RlL25nMi1iczMtbW9kYWwvc3JjL25nMi1iczMtbW9kYWwvY29tcG9uZW50cy9tb2RhbC1mb290ZXIudHMuTW9kYWxGb290ZXJDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICAgICAgPGRpdiBjbGFzcz1cIm1vZGFsLWZvb3RlclwiPlxuICAgICAgICAgICAgPG5nLWNvbnRlbnQ+PC9uZy1jb250ZW50PlxuICAgICAgICAgICAgPGJ1dHRvbiAqbmdJZj1cInNob3dEZWZhdWx0QnV0dG9uc1wiIHR5cGU9XCJidXR0b25cIiBjbGFzcz1cImJ0biBidG4tZGVmYXVsdFwiIGRhdGEtZGlzbWlzcz1cIm1vZGFsXCIgKGNsaWNrKT1cIm1vZGFsLmRpc21pc3MoKVwiPnt7ZGlzbWlzc0J1dHRvbkxhYmVsfX08L2J1dHRvbj5cbiAgICAgICAgICAgIDxidXR0b24gKm5nSWY9XCJzaG93RGVmYXVsdEJ1dHRvbnNcIiB0eXBlPVwiYnV0dG9uXCIgY2xhc3M9XCJidG4gYnRuLXByaW1hcnlcIiAoY2xpY2spPVwibW9kYWwuY2xvc2UoKVwiPnt7Y2xvc2VCdXR0b25MYWJlbH19PC9idXR0b24+XG4gICAgICAgIDwvZGl2PlxuICAgICIsIjxtb2RhbC1mb290ZXI+PC9tb2RhbC1mb290ZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7OztvQkNHWTtNQUFBO01BQUE7UUFBQTtRQUFBO1FBQThGO1VBQUE7VUFBQTtRQUFBO1FBQTlGO01BQUEsZ0NBQXdIOzs7UUFBQTtRQUFBOzs7O29CQUN4SDtNQUFBO01BQUE7UUFBQTtRQUFBO1FBQXlFO1VBQUE7VUFBQTtRQUFBO1FBQXpFO01BQUEsZ0NBQWlHOzs7UUFBQTtRQUFBOzs7O29CQUo3RyxrREFDUTtNQUFBO01BQUEsMERBQTBCO01BQUEsMENBQ3RCLGtCQUF5QjtNQUFBLG1DQUN6QjtNQUFBLHFEQUFBO01BQUE7TUFBdUosc0RBQ3ZKO1VBQUE7YUFBQTtVQUFBLGlDQUE4SDtNQUM1SDs7SUFGTTtJQUFSLFdBQVEsU0FBUjtJQUNRO0lBQVIsV0FBUSxTQUFSOzs7O29CQ0paO01BQUE7cUNBQUEsVUFBQTtNQUFBOzs7OzsifQ==
